dist: bionic
language: python
python:
- '3.7'
services:
  - docker
before_install:
  - docker build . -t rime
script:
  - docker run --rm -ti -v `pwd`/BDD:/rime_taigi_poj_hanlo/BDD rime bash ./runBehaveBDD.sh

